# name: Deploy React App

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     name: deploy app
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [ "12.x" ]
#       steps:
#         - uses: actions/checkout@v2
#           with:
#             fetch-depth: 0
#         - uses: actions/setup-node@v1
#           with:
#             node-version: ${{matrix.node-version}}
#         - name: install packages
#           run: npm install
#         - name: registry github user
#           run: /
#             git config --global user.mail <email>
#             git config --global user.name <name>
#         - name: deploy the app
#           run: npm run deploy
#           env:
#             TOKEN: ${{ secrets.TOKEN }}





name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    step:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.4'

      - name: Install
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: tiltedveggie/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages